name: 기능 요청
description: 새로운 기능 또는 개선 사항을 제안해주세요
title: "[기능 요청] "
labels: ["feature", "enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        🙌 기능 요청을 해주셔서 감사합니다! 아래 항목들을 가능한 자세히 작성해주세요.

  - type: input
    id: summary
    attributes:
      label: 요약
      description: 요청하고자 하는 기능을 한 줄로 간단히 설명해주세요.
      placeholder: 예) 사용자 알림 기능 추가
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 상세 설명
      description: 어떤 기능인지, 왜 필요한지, 구체적으로 설명해주세요.
      placeholder: |
        - 어떤 문제를 해결하려는 기능인가요?
        - 기존에는 어떻게 처리하고 있었나요?
        - 어떤 방식으로 동작하길 기대하나요?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 대안
      description: 고려해본 다른 대안이 있다면 작성해주세요.
      placeholder: |
        예) 슬랙 알림 대신 이메일을 사용하는 것도 고려했지만, 실시간성이 떨어집니다.

  - type: textarea
    id: additional-context
    attributes:
      label: 추가 정보
      description: 이슈와 관련된 스크린샷, 링크, 참고 자료가 있다면 첨부해주세요.
